---
title: "stt simulations"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
```

```{r}

weight_u<-list()
weight_U<-list()
```


Not relative
```{r}
weight_u<-list()
weight_U<-list()
for(i in 1:9){
m<-runif(1,min=0.05,max=0.5) #ln of desired mean velocity
s<-runif(1,min=0.01,max=0.2)
l<-runif(1,min=1,max=7) #perc cover to low vel
h<-runif(1,min=0.1,max=1.2) #perc cover to high vel
#ln of desired sd velocity
vel_patch <- as.data.frame(rnorm(30,mean = m, sd = s))
colnames(vel_patch)<- c("u") #velocity data
data<- mutate(vel_patch, coverage = ifelse(u > 0.1, h, l)) #change accordingly
data$cover<- data$coverage/(sum(data$coverage)) #covergae data based on velocity   
data$U<- 11.197*((data$u)^0.4419) #uptake based on known power function
data$weight_U<-data$U*data$cover #weighted U based on variaton in velocity
weight_u[[i]]<-mean(data$u)
weight_U[[i]]<-sum(data$weight_U,na.rm = T)
}
plot(as.vector(weight_u),as.vector(weight_U))

```


 relative
```{r}
weight_u<-list()
weight_U<-list()
for(i in 1:999){
m<-runif(1,min=0.05,max=0.5) #ln of desired mean velocity
s<-runif(1,min=0.01,max=0.2)
l<-runif(1,min=10,max=20) #perc cover to low vel
h<-runif(1,min=0.1,max=0.5) #perc cover to high vel
#ln of desired sd velocity
vel_patch <- as.data.frame(rnorm(30,mean = m, sd = s))
colnames(vel_patch)<- c("u") #velocity data
data<- mutate(vel_patch, coverage = ifelse(u > 0.1, h, l)) #change accordingly
data$cover<- data$coverage/(sum(data$coverage)) #covergae data based on velocity   
data$U<- 11.197*((data$u)^0.4419) #uptake based on known power function
data$weight_U<-data$U*data$cover #weighted U based on variaton in velocity
weight_u[[i]]<-mean(data$u)
weight_U[[i]]<-sum(data$weight_U,na.rm = T)
}
weight_U<-as.data.frame(as.numeric(weight_U))
colnames(weight_U)<- c("U")
weight_U$U<-weight_U$U/sum(weight_U$U)
plot(as.vector(weight_u),weight_U$U)

```

```{r}
    data$U<- 11.197*((data$weight_u)^0.4419)
    data$firstU<-11.197*0.44419*((data$weight_u)^0.4419-1)
    data$secondU<- 11.197*0.4419*(0.4419-1)*((data$weight_u)^((0.4419-1)-1))

```

